### ISSUE TITLE
overwrite doesn't seem to understand `~`

### ISSUE THREAD

**Issue by ryansch** [rktjmp/shipwright.nvim#10]
When using `{overwrite, "~/.dotfiles/kitty/lunarized.conf"})`, I receive a "No such file or directory" error.

If I change that line to `{overwrite, "/home/ubuntu/.dotfiles/kitty/lunarized.conf"})`, then it works as expected.

**Comment by rktjmp** [comment]
Yep, this is as designed. You can use the built in vim function `vim.fn.expand()` to expand `~`, but beware it also expands other symbols, which is why shipwright doesn't do it automatically.

**Comment by ryansch** [comment]
It might be worth putting something in the README.
