### ISSUE TITLE
Use of functions append or prepend with a table raises an error

### ISSUE THREAD

**Issue by fedepujol** [rktjmp/shipwright.nvim#3]
When trying to use either the append or prepend functions with a table I get an error in the overwrite function.

Information:
NeoVim Version: v0.5.1
OS: Windows 10

How to duplicate:
```lua
local theme = require('lush_themes.theme')
local lushwright = require('shipwright.transform.lush')

run(theme,
    lushwright.to_vimscript,
    lushwright.vim_compatible_vimscript,
    -- the error is the same with prepend
    -- {prepend, {"set background=dark"},
    {append, {"set background=dark"},
    {overwrite, "colors/theme"}
)
```

Run: `:Shipwright`

Result:
`E5108: Error executing lua ...\site\pack\paqs\start\shipwright.nvim\lua\shipwright.lua:18: ...t\shipwright.nvim\lua\shipwright\transform\overwrite.lua:10: attempt to concatenate local 'line' (a table value)
`

It's seems ok if I only use it with a string and not a table.

**Comment by rktjmp** [comment]
Thanks, the tests were using the wrong assert so the bug wasn't caught.
