### ISSUE TITLE
Odd behaviour

### ISSUE THREAD

**Issue by fedepujol** [rktjmp/shipwright.nvim#4]
Hi! Awesome tool by the way!

I'm trying to export a few colorschemes (one at a time) and the problem is that sometimes it works and sometimes it doesn't (the file doesn't get overwritten).

Even if I delete the file, and then export the new one, I'll get the original old file (with no changes).  I've been experience this behaviour on Linux and Windows as well. Checked the file and folder permissions and it was a dead end.

Here it's my "export" file:
```lua
local theme = require('lush_theme.cosmos.cosmos')
local lushwright = require('shipwright.transform.lush')
local name = 'cosmos'

-- Call run and give the colorscheme theme
---@diagnostic disable = undefined-global
run(theme,
	-- convert to a list of vimscript commands
	lushwright.to_vimscript,
	-- pass it through a vim-compatible script (removes blend)
	lushwright.vim_compatible_vimscript,
	-- Add a few housekeeping lines to make it work
	{prepend, {
		'" Maintainer: Fede Pujol',
		"",
		"set background=dark",
		"hi clear",
		"if exists('syntax_on')",
		"\tsyntax reset",
		"endif",
		"let g:colors_name='"..name.."'",
		""
	}},
	-- write the theme to a file
	{overwrite, "colors/"..name..".vim"}
)
```
I'm running this with `:Shipwright export.lua`.

Is there a way for me to debug?

**Comment by rktjmp** [comment]
You could insert your own transforms for some print debugging at least, so that's a function that takes a list and returns a list

```lua
run(theme,
	-- convert to a list of vimscript commands
	lushwright.to_vimscript,
	-- pass it through a vim-compatible script (removes blend)
	lushwright.vim_compatible_vimscript,

        function(something)
          print(vim.inspect(something))
          return something        
        end,

	-- Add a few housekeeping lines to make it work
	{prepend, {
		'" Maintainer: Fede Pujol',
		"",
		"set background=dark",
		"hi clear",
		"if exists('syntax_on')",
		"\tsyntax reset",
		"endif",
		"let g:colors_name='"..name.."'",
		""
	}},
	-- write the theme to a file
	{overwrite, "colors/"..name..".vim"}
)
```

That might help you track down which part isn't behaving. Annoying that it's not consistently failing though.


Overwrite checks that it can open the file to write but doesn't check that write or close worked (just assumes that if open was good, the rest is fine). Maybe that's the problem (or may be helpful to debug).

https://github.com/rktjmp/shipwright.nvim/blob/a3fee9725346eba3eacba36989c906a550a32ae7/lua/shipwright/transform/overwrite.lua#L1-L16

Possibly one of the transforms isn't returning what it should. I can try to take a deeper look in a day or two. First thing I would do is check that overwrite is actually getting lines to write.

**Comment by fedepujol** [comment]
After inserting a few functions in the middle to see what was going on, I've realized that it wasn't an error after all.

The problem that I've got was that Lua didn't reload the module `lush_theme.theme.theme` and It was using the previously one. Because of that, `overwrite` was giving me the old changes and not the new ones.

All I've got to do is, restarting my neovim session after some changes and then do the export part (a little tedious to be honest).

Thanks for the help!

**Comment by rktjmp** [comment]
You can remove the package from lua's "loaded packages" table, then it gets reloaded fresh when you call `require`. Then you wont have to restart nvim.

There is an example in lush-templates `.vim` file: https://github.com/rktjmp/lush-template/blob/main/colors/lush_template.vim

```viml
" By setting our module to nil, we clear lua's cache,
" which means the require ahead will *always* occur.
"
" This isn't strictly required but it can be a useful trick if you are
" incrementally editing your config a lot and want to be sure your themes
" changes are being picked up without restarting neovim.
"
" Note if you're working in on your theme and have :Lushify'd the buffer,
" your changes will be applied with our without the following line.
"
" The performance impact of this call can be measured in the hundreds of
" *nanoseconds* and such could be considered "production safe".
lua package.loaded['lush_theme.lush_template'] = nil
```

So you could put something similar at the start of your build file:

```lua
-- ensure we build from latest on-disk code
package.loaded['lush_theme.cosmos.cosmos'] = nil
local theme = require('lush_theme.cosmos.cosmos')
```

**Comment by fedepujol** [comment]
I was trying to do something like that but with no success becuase:

```lua
-- I was using this:
package.loaded.lush_theme.cosmos.cosmos = nil

-- Instead of this:
package.loaded["lush_theme.comos.cosmos"] = nil
```

Thanks for the tip!
